// This file is auto-generated by figma2assets plugin. Do not edit manually.
import { AutoAssetMap, IAutoAssetsConfig } from "./types";

export const assetsCoreAutoAssetsConst = {
  uiDialogBgLightNine40: {
    name: "uiDialogBgLightNine40",
    url: "./assets/atlases/assets-core.png",
    frameName: "ui.dialog.bg.light.nine.40.png",
    width: 1295,
    height: 517,
    x: 269,
    y: 241,
    kind: "nine",
    ninePadding: 40,
  },
  iconBackGold: {
    name: "iconBackGold",
    url: "./assets/atlases/assets-core.png",
    frameName: "icon-back-gold.png",
    width: 75,
    height: 80,
    x: 1474,
    y: 257,
    kind: "image",
  },
  selectStyleTitle: {
    name: "selectStyleTitle",
    url: "./assets/atlases/assets-core.png",
    frameName: "select-style-title.png",
    width: 363,
    height: 34,
    x: 757,
    y: 279,
    kind: "image",
  },
  selectStyleCardsPreview: {
    name: "selectStyleCardsPreview",
    url: "./assets/atlases/assets-core.png",
    frameName: "select-style-cards-preview.png",
    width: 400,
    height: 234,
    x: 713,
    y: 398,
    kind: "image",
  },
  selectStyleCardBacksPreview: {
    name: "selectStyleCardBacksPreview",
    url: "./assets/atlases/assets-core.png",
    frameName: "select-style-card-backs-preview.png",
    width: 363,
    height: 202,
    x: 1148,
    y: 405,
    kind: "image",
  },
  selectStyleWallpaperPreview: {
    name: "selectStyleWallpaperPreview",
    url: "./assets/atlases/assets-core.png",
    frameName: "select-style-wallpaper-preview.png",
    width: 360,
    height: 202,
    x: 323,
    y: 406,
    kind: "image",
  },
  selectStyleButtonWallpapers: {
    name: "selectStyleButtonWallpapers",
    url: "./assets/atlases/assets-core.png",
    frameName: "select-style-button-wallpapers.png",
    width: 334,
    height: 90,
    x: 336,
    y: 619,
    kind: "image",
  },
  selectStyleButtonCards: {
    name: "selectStyleButtonCards",
    url: "./assets/atlases/assets-core.png",
    frameName: "select-style-button-cards.png",
    width: 334,
    height: 90,
    x: 746,
    y: 619,
    kind: "image",
  },
  selectStyleButtonBg: {
    name: "selectStyleButtonBg",
    url: "./assets/atlases/assets-core.png",
    frameName: "select-style-button-bg.png",
    width: 334,
    height: 90,
    x: 1163,
    y: 619,
    kind: "image",
  },
} as const;

export type AutoAssetName = keyof typeof assetsCoreAutoAssetsConst;

export const assetsCoreAutoAssetOrder: readonly AutoAssetName[] = [
  "uiDialogBgLightNine40",
  "iconBackGold",
  "selectStyleTitle",
  "selectStyleCardsPreview",
  "selectStyleCardBacksPreview",
  "selectStyleWallpaperPreview",
  "selectStyleButtonWallpapers",
  "selectStyleButtonCards",
  "selectStyleButtonBg",
];

export const assetsCoreAutoAssetsConfig: IAutoAssetsConfig = {
  images: assetsCoreAutoAssetsConst,
  preload: {
    atlases: [
      {
        name: "assets-core",
        pngUrl: "./assets/atlases/assets-core.png",
        jsonUrl: "./assets/atlases/assets-core.json",
      },
    ],
  },
} as const;

export const assetsCoreAutoAssets: AutoAssetMap = assetsCoreAutoAssetsConfig.images;
export const assetsCoreAutoAtlas = assetsCoreAutoAssetsConfig.preload.atlases[0];

/**
 * Preloads the generated atlas for this pack.
 */
export function preloadAssetsCoreAssets(scene: Phaser.Scene): void {
  assetsCoreAutoAssetsConfig.preload.atlases.forEach((atlas) => {
    if (scene.textures.exists(atlas.pngUrl)) return;
    scene.load.atlas(atlas.pngUrl, atlas.pngUrl, atlas.jsonUrl);
  });
}
