// This file is auto-generated by figma2assets plugin. Do not edit manually.
{{imports}}

{{textConstants}}{{assetConstants}}export interface {{propsInterfaceName}} {
  readonly scene: Phaser.Scene;
  readonly width?: number;
  readonly height?: number;
  readonly fontSize?: number;
  readonly locale?: string;
}

export class {{className}} extends Phaser.GameObjects.Container {
  constructor(protected props: {{propsInterfaceName}}) {
    super(props.scene, 0, 0);
{{constructorBody}}
  }
}

{{factoryFunction}}
