// This file is auto-generated by figma2assets plugin. Do not edit manually.
import { assetsCoreAutoAssets } from "./assets-core-assets";
import { createView } from "./utils";
import { IAutoViewData } from "./types";

export const viewStyleSettingsData: IAutoViewData = {
  width: 1279,
  height: 501,
  children: [
    {
      asset: assetsCoreAutoAssets.uiDialogBgLightNine40,
      x: -8,
      y: -8,
      width: 1295,
      height: 517,
    },
    {
      asset: assetsCoreAutoAssets.iconBackGold,
      x: 1197,
      y: 8,
      width: 75,
      height: 80,
    },
    {
      asset: assetsCoreAutoAssets.selectStyleTitle,
      x: 480,
      y: 30,
      width: 363,
      height: 34,
    },
    {
      asset: assetsCoreAutoAssets.selectStyleWallpaperPreview,
      x: 46,
      y: 157,
      width: 360,
      height: 202,
    },
    {
      asset: assetsCoreAutoAssets.selectStyleButtonWallpapers,
      x: 59,
      y: 370,
      width: 334,
      height: 90,
    },
    {
      asset: assetsCoreAutoAssets.selectStyleCardBacksPreview,
      x: 871,
      y: 156,
      width: 363,
      height: 202,
    },
    {
      asset: assetsCoreAutoAssets.selectStyleButtonBg,
      x: 886,
      y: 370,
      width: 334,
      height: 90,
    },
    {
      asset: assetsCoreAutoAssets.selectStyleCardsPreview,
      x: 436,
      y: 149,
      width: 400,
      height: 234,
    },
    {
      asset: assetsCoreAutoAssets.selectStyleButtonCards,
      x: 469,
      y: 370,
      width: 334,
      height: 90,
    },
  ],
};

export function viewStyleSettings(scene: Phaser.Scene): Phaser.GameObjects.Container {
  return createView(scene, viewStyleSettingsData);
}

