// This file is auto-generated by figma2assets plugin. Do not edit manually.
import { addAssetImage, addAssetNine } from "./utils";
import { assetsCoreAutoAssets, assetsCoreAutoAssetOrder, AutoAssetName, preloadAssetsCoreAssets } from "./assets-core-assets";

export class AssetsCoreScene extends Phaser.Scene {
  constructor() {
    super({ key: "AssetsCoreScene" });
  }

  preload(): void {
    preloadAssetsCoreAssets(this);
  }

  create(): void {
    assetsCoreAutoAssetOrder.forEach((assetName: AutoAssetName) => {
      const asset = assetsCoreAutoAssets[assetName];
      if (asset.kind === "nine") {
        addAssetNine({ scene: this, asset });
        return;
      }
      addAssetImage({ scene: this, asset });
    });
  }
}

