// This file is auto-generated by figma2assets plugin. Do not edit manually.
import {
  IAddAssetImageProps,
  IAddAssetNineProps,
  PosObject, VisibleObject
} from "../types";

/**
 * Ставит объект по визуальному левому верхнему углу независимо от origin.
 */
export function setLeftTop<T extends PosObject>(item: T, left: number, top: number): T {
  const bounds = item.getBounds();
  const dX = left - bounds.left;
  const dY = top - bounds.top;
  item.setPosition(item.x + dX, item.y + dY);
  return item;
}

/**
 * Центрирует target по фактическим bounds base.
 */
export function center(
  base: Phaser.GameObjects.GameObject & PosObject,
  target: Phaser.GameObjects.GameObject & PosObject,
): void {
  const baseBounds = base.getBounds();
  const targetBounds = target.getBounds();

  target.setPosition(
    target.x + baseBounds.centerX - targetBounds.centerX,
    target.y + baseBounds.centerY - targetBounds.centerY,
  );
}

/**
 * Создает image из atlas и ставит его в координаты Figma.
 */
export function addAssetImage(props: IAddAssetImageProps): Phaser.GameObjects.Image {
  const { scene, asset, x, y } = props;
  const targetX = x ?? asset.x;
  const targetY = y ?? asset.y;
  const imageNode = new Phaser.GameObjects.Image(scene, 0, 0, asset.url, asset.frameName ?? undefined);
  imageNode.name = asset.name || "";
  return setLeftTop(imageNode, targetX, targetY);
}

/**
 * Создает nine-slice из atlas и ставит его в координаты Figma.
 */
export function addAssetNine(props: IAddAssetNineProps): Phaser.GameObjects.NineSlice {
  const { scene, asset, width, height, x, y } = props;
  const padding = asset.ninePadding ?? 20;
  const targetWidth = width ?? asset.width;
  const targetHeight = height ?? asset.height;
  const targetX = x ?? asset.x;
  const targetY = y ?? asset.y;

  const nineSliceNode = new Phaser.GameObjects.NineSlice(
      scene,
      0,
      0,
      asset.url,
      asset.frameName ?? undefined,
      targetWidth,
      targetHeight,
      padding,
      padding,
      padding,
      padding,
  );

  nineSliceNode.name = asset.name || "";
  return setLeftTop(nineSliceNode, targetX, targetY);
}

/** Сделать switch из контейнера, первые 2 children считаются on-off состояниями **/
export function makeSwitch({ initState, view, onSwitch }: {
  initState: boolean;
  view: Phaser.GameObjects.Container;
  onSwitch: (switched: boolean)=>void;
}){
  const onChild = view.getAll()[0] as unknown as VisibleObject;
  const offChild = view.getAll()[1] as unknown as VisibleObject;
  let state = initState;

  const updateState = (newState:boolean)=>{
    state = newState;
    onChild.setVisible(state);
    offChild.setVisible(!state);
  }

  const handleSwitch = ()=>{
    updateState(!state);
    onSwitch(state);
  };

  makeContainerInteractive(view);
  view.on(Phaser.Input.Events.GAMEOBJECT_POINTER_DOWN, handleSwitch);
  updateState(state);
  return view;
}





/** решает кучу проблем с дефолтным setInteractive **/
export function makeContainerInteractive (obj: Phaser.GameObjects.Container){
  /**
   * getBounds возвращает видимую область контейнера в world-координатах.
   * Для hitArea нужны локальные координаты самого контейнера.
   */
  const bounds = obj.getBounds();
  const matrix = obj.getWorldTransformMatrix();

  /**
   * Переводим углы видимого прямоугольника обратно из world в local.
   * Берем все 4 угла, чтобы корректно пережить scale/rotation/parent container.
   */
  const topLeft = matrix.applyInverse(bounds.left, bounds.top);
  const topRight = matrix.applyInverse(bounds.right, bounds.top);
  const bottomLeft = matrix.applyInverse(bounds.left, bounds.bottom);
  const bottomRight = matrix.applyInverse(bounds.right, bounds.bottom);

  /**
   * Собираем локальный bounding box из переведенных углов.
   */
  const left = Math.min(topLeft.x, topRight.x, bottomLeft.x, bottomRight.x);
  const right = Math.max(topLeft.x, topRight.x, bottomLeft.x, bottomRight.x);
  const top = Math.min(topLeft.y, topRight.y, bottomLeft.y, bottomRight.y);
  const bottom = Math.max(topLeft.y, topRight.y, bottomLeft.y, bottomRight.y);
  const width = right - left;
  const height = bottom - top;

  obj.setSize(width, height);

  /**
   * Phaser при проверке input сам добавляет displayOriginX/Y к локальной точке.
   * Поэтому hitArea надо хранить в координатах с таким же origin-сдвигом.
   */
  const hitArea = new Phaser.Geom.Rectangle(
      left + obj.displayOriginX,
      top + obj.displayOriginY,
      width,
      height,
  );

  /**
   * Если input уже был включен, setInteractive только включит старый InteractiveObject
   * и не пересоздаст hitArea. Поэтому обновляем существующий input напрямую.
   */
  if (obj.input) {
    obj.input.enabled = true;
    obj.input.hitArea = hitArea;
    obj.input.hitAreaCallback = Phaser.Geom.Rectangle.Contains;
    obj.input.customHitArea = true;
    obj.input.cursor = "pointer";
  } else {
    obj.setInteractive({
      hitArea,
      hitAreaCallback: Phaser.Geom.Rectangle.Contains,
      useHandCursor: true,
    });
  }

  return obj;
}
