// This file is auto-generated by figma2assets plugin. Do not edit manually.
import { setLeftTop } from "../utils/utils";

const viewStyleSettingsAssets = {
  "uiDialogBgLightNine40": {
    "asset": {
      "name": "uiDialogBgLightNine40",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "ui.dialog.bg.light.nine.40.png",
      "width": 1295,
      "height": 517,
      "x": 269,
      "y": 241,
      "kind": "nine",
      "ninePadding": 40
    },
    "x": -8,
    "y": -8,
    "width": 1295,
    "height": 517
  },
  "iconBackGold": {
    "asset": {
      "name": "iconBackGold",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "icon-back-gold.png",
      "width": 75,
      "height": 80,
      "x": 1474,
      "y": 257,
      "kind": "image"
    },
    "x": 1197,
    "y": 8,
    "width": 75,
    "height": 80
  },
  "selectStyleTitle": {
    "asset": {
      "name": "selectStyleTitle",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "select-style-title.png",
      "width": 363,
      "height": 34,
      "x": 757,
      "y": 279,
      "kind": "image"
    },
    "x": 480,
    "y": 30,
    "width": 363,
    "height": 34
  },
  "selectStyleWallpaperPreview": {
    "asset": {
      "name": "selectStyleWallpaperPreview",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "select-style-wallpaper-preview.png",
      "width": 360,
      "height": 202,
      "x": 323,
      "y": 406,
      "kind": "image"
    },
    "x": 46,
    "y": 157,
    "width": 360,
    "height": 202
  },
  "selectStyleButtonWallpapers": {
    "asset": {
      "name": "selectStyleButtonWallpapers",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "select-style-button-wallpapers.png",
      "width": 334,
      "height": 90,
      "x": 336,
      "y": 619,
      "kind": "image"
    },
    "x": 59,
    "y": 370,
    "width": 334,
    "height": 90
  },
  "selectStyleCardBacksPreview": {
    "asset": {
      "name": "selectStyleCardBacksPreview",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "select-style-card-backs-preview.png",
      "width": 363,
      "height": 202,
      "x": 1148,
      "y": 405,
      "kind": "image"
    },
    "x": 871,
    "y": 156,
    "width": 363,
    "height": 202
  },
  "selectStyleButtonBg": {
    "asset": {
      "name": "selectStyleButtonBg",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "select-style-button-bg.png",
      "width": 334,
      "height": 90,
      "x": 1163,
      "y": 619,
      "kind": "image"
    },
    "x": 886,
    "y": 370,
    "width": 334,
    "height": 90
  },
  "selectStyleCardsPreview": {
    "asset": {
      "name": "selectStyleCardsPreview",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "select-style-cards-preview.png",
      "width": 400,
      "height": 234,
      "x": 713,
      "y": 398,
      "kind": "image"
    },
    "x": 436,
    "y": 149,
    "width": 400,
    "height": 234
  },
  "selectStyleButtonCards": {
    "asset": {
      "name": "selectStyleButtonCards",
      "url": "./assets/atlases/assets-core.png",
      "frameName": "select-style-button-cards.png",
      "width": 334,
      "height": 90,
      "x": 746,
      "y": 619,
      "kind": "image"
    },
    "x": 469,
    "y": 370,
    "width": 334,
    "height": 90
  }
} as const;

export interface IViewStyleSettingsProps {
  readonly scene: Phaser.Scene;
  readonly width?: number;
  readonly height?: number;
  readonly fontSize?: number;
  readonly locale?: string;
}

export class ViewStyleSettings extends Phaser.GameObjects.Container {
  constructor(protected props: IViewStyleSettingsProps) {
    super(props.scene, 0, 0);
    const scene = props.scene;
    const viewWidth = props.width ?? 1279;
    const viewHeight = props.height ?? 501;
    this.name = "viewStyleSettings";
    this.setSize(viewWidth, viewHeight);

    Object.values(viewStyleSettingsAssets).forEach((data) => {
      const asset = data.asset;
      const node = asset.kind === "nine"
        ? new Phaser.GameObjects.NineSlice(
          scene,
          0,
          0,
          asset.url,
          asset.frameName,
          data.width,
          data.height,
          asset.ninePadding ?? 20,
          asset.ninePadding ?? 20,
          asset.ninePadding ?? 20,
          asset.ninePadding ?? 20,
        )
        : new Phaser.GameObjects.Image(scene, 0, 0, asset.url, asset.frameName);

      node.name = asset.name || "";
      setLeftTop(node, data.x - viewWidth / 2, data.y - viewHeight / 2);
      this.add(node);
    });
  }
}

export function createViewStyleSettings(props: IViewStyleSettingsProps): ViewStyleSettings {
  return new ViewStyleSettings(props);
}
