// This file is auto-generated by figma2assets plugin. Do not edit manually.
export type AutoAssetKind = "image" | "nine";

export interface IAutoAssetData {
  readonly name: string;
  readonly url: string;
  readonly frameName: string;
  readonly width: number;
  readonly height: number;
  readonly x: number;
  readonly y: number;
  readonly kind: AutoAssetKind;
  readonly ninePadding?: number;
}

export interface IAddAssetImageProps {
  scene: Phaser.Scene;
  asset: IAutoAssetData;
  x?: number;
  y?: number;
}

export interface IAddAssetNineProps {
  scene: Phaser.Scene;
  asset: IAutoAssetData;
  width?: number;
  height?: number;
  x?: number;
  y?: number;
}

export interface PosObject {
  x: number;
  y: number;
  getBounds(): Phaser.Geom.Rectangle; // критически важно для совместимости с Align
  setPosition(x: number, y: number): this;
}


export type PosGameObject = Phaser.GameObjects.GameObject & PosObject;

export interface IAutoViewAssetChildData {
  readonly type?: string;
  readonly asset: IAutoAssetData;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

export interface IAutoViewLayoutData {
  readonly name?: string;
  readonly button?: boolean;
  readonly width: number;
  readonly height: number;
}

export interface IAutoViewData extends IAutoViewLayoutData {
  /**
   * Дети лежат в object literal, чтобы generated constants сохраняли читаемые ключи из Figma.
   */
  readonly children: {
    readonly [name: string]: IAutoViewChildData;
  };
}

export interface IAutoViewRefChildData extends IAutoViewData {
  readonly type: string;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

export interface ITextViewOptions {
  readonly text?: string;
  readonly style?: Partial<Phaser.Types.GameObjects.Text.TextStyle>;
  readonly locale?: string;
}

export interface IAutoTextLocaleMap {
  readonly en: string;
  readonly ru: string;
  readonly [locale: string]: string;
}

export interface IAutoTextData {
  readonly name?: string;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
  readonly localeMap: IAutoTextLocaleMap;
  readonly style: Partial<Phaser.Types.GameObjects.Text.TextStyle>;
}

export interface IAutoTextChildData {
  readonly type: string;
  readonly text: IAutoTextData;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

export interface IAutoTextRefChildData {
  readonly type: string;
  readonly text: IAutoTextData;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

export type IAutoViewChildData =
  | IAutoViewAssetChildData
  | IAutoViewRefChildData
  | IAutoTextRefChildData;
