// This file is auto-generated by figma2assets plugin. Do not edit manually.
export type AutoAssetKind = "image" | "nine";

export interface IAutoAssetData {
  readonly name: string;
  readonly url: string;
  readonly frameName: string;
  readonly width: number;
  readonly height: number;
  readonly x: number;
  readonly y: number;
  readonly kind: AutoAssetKind;
  readonly ninePadding?: number;
}

export interface IAddAssetImageProps {
  scene: Phaser.Scene;
  asset: IAutoAssetData;
  x?: number;
  y?: number;
}

export interface IAddAssetNineProps {
  scene: Phaser.Scene;
  asset: IAutoAssetData;
  width?: number;
  height?: number;
  x?: number;
  y?: number;
}

export interface PosObject {
  x: number;
  y: number;
  getBounds(): { left: number; top: number };
  setPosition(x: number, y: number): this;
}

export interface IAutoViewAssetChildData {
  readonly type?: "asset";
  readonly asset: IAutoAssetData;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

export interface IAutoViewData {
  readonly name?: string;
  readonly button?: true;
  readonly width: number;
  readonly height: number;
  readonly children: readonly IAutoViewChildData[];
}

export interface IAutoViewRefChildData {
  readonly type: "view";
  readonly view: IAutoViewData;
  readonly x: number;
  readonly y: number;
  readonly width: number;
  readonly height: number;
}

export type IAutoViewChildData = IAutoViewAssetChildData | IAutoViewRefChildData;
