// This file is auto-generated by figma2assets plugin. Do not edit manually.
import {
  IAddAssetImageProps,
  IAddAssetNineProps, IAutoTextChildData,
  IAutoTextData,
  IAutoViewAssetChildData,
  IAutoViewChildData,
  IAutoViewData,
  IAutoViewLayoutData,
  IAutoViewRefChildData,
  ITextViewOptions,
  PosGameObject,
  PosObject
} from "./types";

/**
 * Ставит объект по визуальному левому верхнему углу независимо от origin.
 */
export function setLeftTop<T extends PosObject>(item: T, left: number, top: number): T {
  const bounds = item.getBounds();
  const dX = left - bounds.left;
  const dY = top - bounds.top;
  item.setPosition(item.x + dX, item.y + dY);
  return item;
}

/**
 * Создает container с логическим размером для hit-area и layout.
 */
export function con(
    scene: Phaser.Scene,
    x = 0,
    y = 0,
    width = 0,
    height = 0,
): Phaser.GameObjects.Container {
  const container = scene.add.container(x, y);
  container.setSize(width, height);
  return container;
}

/**
 * Создает container из данных view; children здесь не нужны.
 */
export function createContainerFromViewData(
  scene: Phaser.Scene,
  view: IAutoViewLayoutData,
): Phaser.GameObjects.Container {
  const root = con(scene, 0, 0, view.width, view.height);
  root.name = view.name || "";
  root.setSize(view.width, view.height);

  if(view.button){
    root.setData("button", true);

    /** должно идти после setSize! **/
    root.setInteractive({
      useHandCursor: true,
    });
  }

  return root;
}

/**
 * Создает image из atlas и ставит его в координаты Figma.
 */
export function addAssetImage(props: IAddAssetImageProps): Phaser.GameObjects.Image {
  const { scene, asset, x, y } = props;
  const targetX = x ?? asset.x;
  const targetY = y ?? asset.y;
  const imageNode = scene.add.image(0, 0, asset.url, asset.frameName);
  imageNode.name = asset.name || "";
  return setLeftTop(imageNode, targetX, targetY);
}

/**
 * Создает nine-slice из atlas и ставит его в координаты Figma.
 */
export function addAssetNine(props: IAddAssetNineProps): Phaser.GameObjects.NineSlice {
  const { scene, asset, width, height, x, y } = props;
  const padding = asset.ninePadding ?? 20;
  const targetWidth = width ?? asset.width;
  const targetHeight = height ?? asset.height;
  const targetX = x ?? asset.x;
  const targetY = y ?? asset.y;

  const nineSliceNode = scene.add.nineslice(
      0,
      0,
      asset.url,
      asset.frameName,
      targetWidth,
      targetHeight,
      padding,
      padding,
      padding,
      padding,
  );

  nineSliceNode.name = asset.name || "";
  return setLeftTop(nineSliceNode, targetX, targetY);
}

/**
 * Берет локализованный текст с простым fallback по локалям.
 */
function resolveLocaleText(
  localeMap: IAutoTextData["localeMap"],
  locale?: string,
): string {
  const requestedLocale = String(locale || "en");
  const nextText =
    localeMap[requestedLocale] ??
    localeMap.en ??
    localeMap.ru ??
    "";

  return String(nextText || "");
}

/**
 * Проверяет, что child описывает вложенный view.
 */
function isViewRefChild(child: IAutoViewChildData): child is IAutoViewRefChildData {
  return child.type === "view" && "children" in child;
}

/**
 * Проверяет, что child описывает текстовый объект.
 */
function isTextRefChild(child: IAutoViewChildData): child is IAutoTextChildData {
  return child.type === "text" && "text" in child;
}

/**
 * Проверяет, что child описывает atlas asset.
 */
function isAssetChild(child: IAutoViewChildData): child is IAutoViewAssetChildData {
  return "asset" in child;
}

/**
 * Создает Phaser Text из декларативных text data.
 */
export function createTextView(
  scene: Phaser.Scene,
  textData: IAutoTextData,
  options: ITextViewOptions = {},
): Phaser.GameObjects.Text {
  const style = {
    ...textData.style,
    ...(options.style || {}),
  };
  const hasStaticTextOverride = typeof options.text === "string";
  const initialText = hasStaticTextOverride
    ? String(options.text || "")
    : resolveLocaleText(textData.localeMap, options.locale);

  const textObject = scene.add.text(0, 0, initialText, style);
  textObject.name = textData.name || "";
  textObject.setOrigin(0, 0);
  textObject.setPosition(textData.x || 0, textData.y || 0);

  if (!hasStaticTextOverride) {
    const localeListener = (payload: { locale?: string } | string | null | undefined) => {
      const locale =
        payload && typeof payload === "object"
          ? payload.locale
          : typeof payload === "string"
            ? payload
            : undefined;
      textObject.setText(resolveLocaleText(textData.localeMap, locale));
    };

    scene.events.on("onLocaleChange", localeListener);
    textObject.once(Phaser.GameObjects.Events.DESTROY, () => {
      scene.events.off("onLocaleChange", localeListener);
    });
  }

  return textObject;
}

/**
 * Создает asset child из generated data.
 */
export function createAssetChild(
  scene: Phaser.Scene,
  child: IAutoViewAssetChildData,
): PosGameObject {
  if (child.asset.kind === "nine") {
    return addAssetNine({
      scene,
      asset: child.asset,
      width: child.width,
      height: child.height,
      x: child.x,
      y: child.y,
    });
  }

  return addAssetImage({
    scene,
    asset: child.asset,
    x: child.x,
    y: child.y,
  });
}

/**
 * Создает text child из generated data.
 */
export function createTextChild(
  scene: Phaser.Scene,
  child: IAutoTextChildData,
): Phaser.GameObjects.Text {
  const textNode = createTextView(scene, child.text);
  textNode.setPosition(child.x, child.y);
  return textNode;
}

/**
 * Добавляет child во view с переводом Figma-координат в координаты container.
 */
export function addChildToView(
  view: Phaser.GameObjects.Container,
  child: PosGameObject,
  viewData: IAutoViewLayoutData,
): void {
  child.x -= viewData.width/2;
  child.y -= viewData.height/2;
  view.add(child);
}

/**
 * Legacy helper для старого generated code с nested view.
 */
export function addNestedViewToView(
  view: Phaser.GameObjects.Container,
  child: PosGameObject,
  viewData: IAutoViewLayoutData,
  childData: IAutoViewRefChildData,
): void {
  setLeftTop(child, childData.x, childData.y);
  addChildToView(view, child, viewData);
}

/**
 * Создает Phaser container из generic view data.
 */
export function createView(scene: Phaser.Scene, view: IAutoViewData): Phaser.GameObjects.Container {
  const root = createContainerFromViewData(scene, view);

  Object.values(view.children).forEach((child) => {
    const viewChild = renderViewChild(scene, child);

    addChildToView(root, viewChild, view);
  });

  return root;
}

/**
 * Рендерит один child через общие asset/text/view helpers.
 */
export function renderViewChild(
  scene: Phaser.Scene,
  child: IAutoViewChildData,
): PosGameObject {
  if (isViewRefChild(child)) {
    const nestedView = createView(scene, child);
    setLeftTop(nestedView, child.x, child.y);
    return nestedView;
  }

  if (isTextRefChild(child)) {
    const textNode = createTextView(scene, child.text);
    textNode.setPosition(child.x, child.y);
    return textNode;
  }

  /**
   * Если child не view и не text, считаем его asset.
   * Это намеренный fallback: generated data валидируется на этапе генерации,
   * а runtime helper не должен ронять игру дополнительным throw.
   */
  const assetChild = child as IAutoViewAssetChildData;

  if (assetChild.asset.kind === "nine") {
    return addAssetNine({
      scene,
      asset: assetChild.asset,
      width: assetChild.width,
      height: assetChild.height,
      x: assetChild.x,
      y: assetChild.y,
    });
  }

  return addAssetImage({
    scene,
    asset: assetChild.asset,
    x: assetChild.x,
    y: assetChild.y,
  });
}
