// This file is auto-generated by figma2assets plugin. Do not edit manually.
import { IAddAssetImageProps, IAddAssetNineProps, IAutoViewChildData, IAutoViewData, PosObject } from "./types";

/**
 * setLeftTop - places an object by its visual left/top regardless of origin.
 */
export function setLeftTop<T extends PosObject>(item: T, left: number, top: number): T {
  const bounds = item.getBounds();
  const dX = left - bounds.left;
  const dY = top - bounds.top;
  item.setPosition(item.x + dX, item.y + dY);
  return item;
}

/**
 * Creates a container with optional logical size.
 */
export function con(
    scene: Phaser.Scene,
    x = 0,
    y = 0,
    width = 0,
    height = 0,
): Phaser.GameObjects.Container {
  const container = scene.add.container(x, y);
  container.setSize(width, height);
  return container;
}

/**
 * Adds an atlas image and positions it by Figma coordinates.
 */
export function addAssetImage(props: IAddAssetImageProps): Phaser.GameObjects.Image {
  const { scene, asset, x, y } = props;
  const targetX = x ?? asset.x;
  const targetY = y ?? asset.y;
  const imageNode = scene.add.image(0, 0, asset.url, asset.frameName);
  return setLeftTop(imageNode, targetX, targetY);
}

/**
 * Adds a nine-slice object and positions it by Figma coordinates.
 */
export function addAssetNine(props: IAddAssetNineProps): Phaser.GameObjects.NineSlice {
  const { scene, asset, width, height, x, y } = props;
  const padding = asset.ninePadding ?? 20;
  const targetWidth = width ?? asset.width;
  const targetHeight = height ?? asset.height;
  const targetX = x ?? asset.x;
  const targetY = y ?? asset.y;

  const nineSliceNode = scene.add.nineslice(
      0,
      0,
      asset.url,
      asset.frameName,
      targetWidth,
      targetHeight,
      padding,
      padding,
      padding,
      padding,
  );

  return setLeftTop(nineSliceNode, targetX, targetY);
}

/**
 * Creates a Phaser container from declarative view data.
 */
export function createView(scene: Phaser.Scene, view: IAutoViewData): Phaser.GameObjects.Container {
  const root = con(scene, 0, 0, view.width, view.height);
  root.name = view.name || "";

  view.children.forEach((child) => {
    root.add(renderViewChild(scene, child));
  });

  if(view.button){
    root.setData("button", true);
    setConInteractive(root);
  }

  return root;
}

/**
 * Renders a view child using the shared asset helpers.
 */
export function renderViewChild(
    scene: Phaser.Scene,
    child: IAutoViewChildData,
): Phaser.GameObjects.GameObject {
  if (child.type === "view") {
    const nestedView = createView(scene, child.view);
    setLeftTop(nestedView, child.x, child.y);
    return nestedView;
  }

  if (child.asset.kind === "nine") {
    return addAssetNine({
      scene,
      asset: child.asset,
      width: child.width,
      height: child.height,
      x: child.x,
      y: child.y,
    });
  }

  return addAssetImage({
    scene,
    asset: child.asset,
    x: child.x,
    y: child.y,
  });
}


/**
 * Делает контейнер интерактивным
 * попутно устанавливает его размер
 * и смещает детей на половину чтобы сохранить анимации от центра
 *  **/
function setConInteractive(con: Phaser.GameObjects.Container):
    Phaser.GameObjects.Container {

  const bounds = con.getBounds();
  con.setSize(bounds.width, bounds.height);
  fixContainerChildPosition(con);

  con.setInteractive({
    useHandCursor: true,
  });

  return con;
}

/** смещаем всех детей контейнера на половину
 * чтобы видимый центр контейнера соответствовал его точке 0, 0 (левый верхний угол)
 **/
function fixContainerChildPosition(con: Phaser.GameObjects.Container):
    Phaser.GameObjects.Container {

  const bounds = con.getBounds();
  const dX = -bounds.width/2;
  const dY = -bounds.height/2;

  con.getAll().forEach((t) => {
    (t as PosObject).x += dX;
    (t as PosObject).y += dY;
  });

  return con;
}
